import { writeFileSync, mkdirSync, existsSync } from "node:fs"
import { resolve, dirname } from "node:path"
import chalk from "chalk"
import { findRulesDir, loadLocalRules, type LocalRule } from "../lib/local-rules.js"

interface GenerateOptions {
  dir?: string
  output?: string
  agent?: string
}

type AgentFormat = "claude-code" | "cursor" | "copilot" | "all"

const MODALITY_PREFIX: Record<string, string> = {
  must: "MUST:",
  should: "SHOULD:",
  may: "MAY:",
}

function formatRulesForAgent(rules: LocalRule[], agent: string): string {
  const lines: string[] = []
  const timestamp = new Date().toISOString().split("T")[0]

  switch (agent) {
    case "claude-code":
      lines.push("# Project Rules")
      lines.push(`# Generated by Rulebound on ${timestamp}`)
      lines.push(`# Source: .rulebound/rules/ (${rules.length} rules)`)
      lines.push("")
      lines.push("## Engineering Standards")
      lines.push("")
      for (const rule of rules) {
        const prefix = MODALITY_PREFIX[rule.modality] ?? "SHOULD:"
        lines.push(`### ${prefix} ${rule.title}`)
        lines.push("")
        // Extract just the bullet points from content
        const bullets = rule.content.split("\n").filter(l => l.startsWith("- "))
        if (bullets.length > 0) {
          for (const bullet of bullets) {
            lines.push(bullet)
          }
        } else {
          // Use first paragraph
          const firstPara = rule.content.split("\n\n").find(p => p.length > 20 && !p.startsWith("#"))
          if (firstPara) lines.push(firstPara.trim())
        }
        lines.push("")
      }
      lines.push("---")
      lines.push("*Auto-generated by [Rulebound](https://github.com/ylcn91/rulebound). Do not edit manually.*")
      break

    case "cursor":
      lines.push("# Project Rules")
      lines.push(`# Generated by Rulebound on ${timestamp}`)
      lines.push("")
      for (const rule of rules) {
        const prefix = MODALITY_PREFIX[rule.modality] ?? "SHOULD:"
        lines.push(`## ${prefix} ${rule.title}`)
        lines.push("")
        const bullets = rule.content.split("\n").filter(l => l.startsWith("- "))
        for (const bullet of bullets) {
          lines.push(bullet)
        }
        if (bullets.length === 0) {
          const firstPara = rule.content.split("\n\n").find(p => p.length > 20 && !p.startsWith("#"))
          if (firstPara) lines.push(firstPara.trim())
        }
        lines.push("")
      }
      break

    case "copilot":
      lines.push(`# GitHub Copilot Instructions`)
      lines.push(`# Generated by Rulebound on ${timestamp}`)
      lines.push("")
      lines.push("Follow these engineering standards for all code generation:")
      lines.push("")
      for (const rule of rules) {
        const prefix = MODALITY_PREFIX[rule.modality] ?? "SHOULD:"
        lines.push(`## ${prefix} ${rule.title}`)
        lines.push("")
        const bullets = rule.content.split("\n").filter(l => l.startsWith("- "))
        for (const bullet of bullets) {
          lines.push(bullet)
        }
        if (bullets.length === 0) {
          const firstPara = rule.content.split("\n\n").find(p => p.length > 20 && !p.startsWith("#"))
          if (firstPara) lines.push(firstPara.trim())
        }
        lines.push("")
      }
      break
  }

  return lines.join("\n") + "\n"
}

const AGENT_FILES: Record<string, string> = {
  "claude-code": "CLAUDE.md",
  cursor: ".cursor/rules.md",
  copilot: ".github/copilot-instructions.md",
}

export async function generateCommand(options: GenerateOptions): Promise<void> {
  const rulesDir = options.dir ?? findRulesDir(process.cwd())

  if (!rulesDir) {
    console.error(chalk.red("No rules directory found."))
    console.error(chalk.dim("Run 'rulebound init' to create one."))
    process.exit(1)
  }

  const rules = loadLocalRules(rulesDir)

  if (rules.length === 0) {
    console.log(chalk.dim("No rules found."))
    return
  }

  const agents: AgentFormat[] = options.agent === "all" || !options.agent
    ? ["claude-code", "cursor", "copilot"]
    : [options.agent as AgentFormat]

  const outputDir = options.output ?? process.cwd()

  console.log()
  console.log(chalk.white("GENERATE AGENT CONFIGS"))
  console.log(chalk.dim(`Source: ${rulesDir} (${rules.length} rules)`))
  console.log(chalk.dim("─".repeat(50)))
  console.log()

  for (const agent of agents) {
    if (agent === "all") continue

    const content = formatRulesForAgent(rules, agent)
    const fileName = AGENT_FILES[agent]
    if (!fileName) continue

    const filePath = resolve(outputDir, fileName)
    const dir = dirname(filePath)

    if (!existsSync(dir)) {
      mkdirSync(dir, { recursive: true })
    }

    writeFileSync(filePath, content)
    console.log(`  ${chalk.white(fileName)} ${chalk.dim(`(${agent})`)}`)
  }

  console.log()
  console.log(chalk.white(`Generated ${agents.length} config file${agents.length === 1 ? "" : "s"}.`))
  console.log(chalk.dim("Commit these files so your AI agents pick them up."))
}
