import type { RuleSeverity, RuleModality } from "@rulebound/engine"
import { existsSync } from "node:fs"
import { join } from "node:path"

export interface ParsedRule {
  readonly title: string
  readonly content: string
  readonly category: string
  readonly severity: string
  readonly modality: string
  readonly tags: readonly string[]
  readonly slug: string
}

const CATEGORY_KEYWORDS: Record<string, readonly string[]> = {
  security: ["secret", "auth", "token", "password", "xss", "injection", "csrf", "cors", "encrypt", "hash", "credential", "sanitiz", "vulnerabilit"],
  architecture: ["pattern", "dependency", "inject", "layer", "module", "structure", "hexagonal", "clean", "solid", "service", "repository"],
  style: ["naming", "format", "lint", "convention", "import", "export", "comment", "indentation", "bracket", "semicolon"],
  testing: ["test", "spec", "coverage", "mock", "stub", "assert", "expect", "tdd", "bdd", "unit test", "integration test"],
  performance: ["cache", "lazy", "memo", "debounce", "throttle", "bundle", "optimize", "performance", "latency"],
  accessibility: ["a11y", "wcag", "aria", "screen reader", "keyboard", "focus", "contrast", "alt text", "semantic"],
  infra: ["docker", "kubernetes", "k8s", "ci", "cd", "deploy", "pipeline", "terraform", "aws", "cloud"],
  workflow: ["git", "branch", "commit", "pr", "review", "merge", "version", "release"],
  documentation: ["doc", "readme", "jsdoc", "tsdoc", "comment", "changelog"],
}

const MUST_PATTERNS = [
  /\bMUST\b/,
  /\bNEVER\b/,
  /\bALWAYS\b/,
  /\bREQUIRED\b/,
  /\bMUST NOT\b/,
  /\bSHALL\b/,
  /\bSHALL NOT\b/,
]

const SHOULD_PATTERNS = [
  /\bSHOULD\b/,
  /\bRECOMMENDED\b/,
  /\bPREFER\b/,
]

function slugify(text: string): string {
  return text
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "")
    .slice(0, 60)
}

function detectCategory(title: string, content: string): string {
  const text = `${title} ${content}`.toLowerCase()

  let bestCategory = "general"
  let bestScore = 0

  for (const [category, keywords] of Object.entries(CATEGORY_KEYWORDS)) {
    const score = keywords.filter((kw) => text.includes(kw)).length
    if (score > bestScore) {
      bestScore = score
      bestCategory = category
    }
  }

  return bestCategory
}

function detectModality(content: string): string {
  if (MUST_PATTERNS.some((p) => p.test(content))) return "must"
  if (SHOULD_PATTERNS.some((p) => p.test(content))) return "should"
  return "may"
}

function detectSeverity(modality: string, content: string): string {
  if (modality === "must") return "error"
  if (modality === "should") return "warning"
  return "info"
}

function extractTags(title: string, content: string): string[] {
  const text = `${title} ${content}`.toLowerCase()
  const tags = new Set<string>()

  const techTerms = [
    "jwt", "oauth", "api", "rest", "graphql", "docker", "kubernetes",
    "react", "nextjs", "typescript", "javascript", "python", "java", "go",
    "sql", "postgres", "redis", "env", "secrets", "ci", "cd",
    "hooks", "components", "state", "props", "ssr", "csr",
    "testing", "coverage", "lint", "format",
  ]

  for (const term of techTerms) {
    if (text.includes(term)) tags.add(term)
  }

  return [...tags].slice(0, 8)
}

interface HeadingSection {
  readonly title: string
  readonly level: number
  readonly content: string
}

function splitByHeadings(markdown: string): HeadingSection[] {
  const lines = markdown.split("\n")
  const sections: HeadingSection[] = []
  let current: { title: string; level: number; lines: string[] } | null = null

  for (const line of lines) {
    const headingMatch = line.match(/^(#{2,3})\s+(.+)$/)
    if (headingMatch) {
      if (current && current.lines.some((l) => l.trim())) {
        sections.push({
          title: current.title,
          level: current.level,
          content: current.lines.join("\n").trim(),
        })
      }
      current = {
        title: headingMatch[2].trim(),
        level: headingMatch[1].length,
        lines: [],
      }
    } else if (current) {
      current.lines.push(line)
    }
  }

  if (current && current.lines.some((l) => l.trim())) {
    sections.push({
      title: current.title,
      level: current.level,
      content: current.lines.join("\n").trim(),
    })
  }

  return sections
}

function stripCodingGuidelinesTag(content: string): string {
  return content
    .replace(/<coding_guidelines>/gi, "")
    .replace(/<\/coding_guidelines>/gi, "")
    .trim()
}

function isMeaningfulSection(section: HeadingSection): boolean {
  const skipTitles = [
    "table of contents", "toc", "index", "generated by",
    "auto-generated", "do not edit",
  ]
  const titleLower = section.title.toLowerCase()
  if (skipTitles.some((s) => titleLower.includes(s))) return false

  const contentLines = section.content.split("\n").filter((l) => l.trim())
  return contentLines.length >= 1
}

export function parseMarkdownToRules(markdown: string, sourceFile?: string): ParsedRule[] {
  const cleaned = stripCodingGuidelinesTag(markdown)
  const sections = splitByHeadings(cleaned)

  if (sections.length === 0) {
    const trimmed = cleaned.trim()
    if (trimmed.length < 10) return []

    const title = sourceFile
      ? sourceFile.replace(/\.[^.]+$/, "").replace(/[_-]/g, " ")
      : "Imported Rule"

    const modality = detectModality(trimmed)
    return [{
      title,
      content: trimmed,
      category: detectCategory(title, trimmed),
      severity: detectSeverity(modality, trimmed),
      modality,
      tags: extractTags(title, trimmed),
      slug: slugify(title),
    }]
  }

  const rules: ParsedRule[] = []

  for (const section of sections) {
    if (!isMeaningfulSection(section)) continue

    const modality = detectModality(section.content)
    const category = detectCategory(section.title, section.content)

    rules.push({
      title: section.title,
      content: section.content,
      category,
      severity: detectSeverity(modality, section.content),
      modality,
      tags: extractTags(section.title, section.content),
      slug: slugify(section.title),
    })
  }

  return rules
}

export function ruleToMarkdown(rule: ParsedRule): string {
  const frontMatter = [
    "---",
    `title: ${rule.title}`,
    `category: ${rule.category}`,
    `severity: ${rule.severity}`,
    `modality: ${rule.modality}`,
    `tags: [${rule.tags.join(", ")}]`,
    "---",
  ].join("\n")

  return `${frontMatter}\n\n# ${rule.title}\n\n${rule.content}\n`
}

export const KNOWN_AGENT_FILES = [
  "CLAUDE.md",
  "AGENTS.md",
  ".cursor/rules.md",
  ".cursorrules",
  ".github/copilot-instructions.md",
] as const

export function detectAgentFiles(cwd: string): string[] {
  return KNOWN_AGENT_FILES.filter((f) => existsSync(join(cwd, f))).map((f) => join(cwd, f))
}
