import { describe, it, expect } from "vitest"
import type {
  DeterministicReport,
  CheckResult,
  RuleStatus,
  AppliedWaiver,
  Waiver,
} from "@rulebound/engine"
import { renderPrMarkdown } from "../commands/check.js"

// Deterministic snapshot fixtures for the pr-markdown renderer.
//
// Rules for stable snapshots:
// - no Date.now / current timestamps in fixtures,
// - no absolute paths (only repo-relative),
// - explicit, stable result ordering (we list results in the order they
//   appear in the array — the renderer preserves input order).
//
// The renderer takes the rerun hint as an argument, so snapshots also
// fix that string instead of letting CLI options leak in.
const RERUN = "rulebound check --base main"

function emptySummary(): DeterministicReport["summary"] {
  return { total: 0, pass: 0, violated: 0, notApplicable: 0, error: 0, blocking: 0, waived: 0 }
}

function makeResult(overrides: Partial<CheckResult> & Pick<CheckResult, "ruleId" | "checkId" | "status">): CheckResult {
  return {
    source: "regex",
    deterministic: true,
    confidence: "exact",
    blocking: true,
    reason: "",
    ...overrides,
  } as CheckResult
}

function makeRuleStatus(overrides: Partial<RuleStatus> & Pick<RuleStatus, "ruleId">): RuleStatus {
  return {
    title: overrides.ruleId,
    checkCount: 1,
    status: "PASS",
    blocking: true,
    ...overrides,
  } as RuleStatus
}

function makeWaiver(overrides: Partial<Waiver> & Pick<Waiver, "rule" | "expires">): Waiver {
  return {
    reason: "tracked",
    owner: "@team",
    ...overrides,
  } as Waiver
}

function makeReport(input: {
  status: DeterministicReport["status"]
  results?: readonly CheckResult[]
  ruleStatuses?: readonly RuleStatus[]
  parseErrors?: readonly { ruleId: string; errors: readonly string[] }[]
  waiversApplied?: readonly AppliedWaiver[]
  summary?: Partial<DeterministicReport["summary"]>
}): DeterministicReport {
  return {
    status: input.status,
    results: input.results ?? [],
    ruleStatuses: input.ruleStatuses ?? [],
    parseErrors: input.parseErrors ?? [],
    waiversApplied: input.waiversApplied ?? [],
    summary: { ...emptySummary(), ...(input.summary ?? {}) },
  }
}

describe("renderPrMarkdown — deterministic snapshots", () => {
  it("case 1: all pass", () => {
    const report = makeReport({
      status: "PASSED",
      summary: { total: 2, pass: 2 },
      ruleStatuses: [
        makeRuleStatus({ ruleId: "security.no-secrets", status: "PASS" }),
        makeRuleStatus({ ruleId: "evidence.has-readme", status: "PASS" }),
      ],
    })
    expect(renderPrMarkdown(report, RERUN)).toMatchInlineSnapshot(`
      "## rulebound check — **PASSED**

      - **Pass:** 2
      - **Violated:** 0
      - **Blocking:** 0
      - **Waived:** 0
      - **Not applicable:** 0
      - **Errors:** 0
      - **Advisory-only rules:** 0

      ### Deterministic blockers

      _None._

      ### Deterministic warnings

      _None._

      ### Waivers applied

      _None._

      ### Analyzer findings

      _No analyzer checks ran._

      ### Repair

      All deterministic checks passed.

      ---
      _Generated by \`rulebound check --format pr-markdown\`._"
    `)
  })

  it("case 2: one deterministic blocker", () => {
    const report = makeReport({
      status: "FAILED",
      summary: { total: 1, violated: 1, blocking: 1 },
      ruleStatuses: [makeRuleStatus({ ruleId: "security.no-secrets", status: "VIOLATED" })],
      results: [
        makeResult({
          ruleId: "security.no-secrets",
          checkId: "regex:AWS_ACCESS_KEY",
          status: "VIOLATED",
          source: "regex",
          blocking: true,
          reason: "Found AWS access key in source",
          evidence: { filePath: "src/config.ts", line: 42 },
        }),
      ],
    })
    expect(renderPrMarkdown(report, RERUN)).toMatchInlineSnapshot(`
      "## rulebound check — **FAILED**

      - **Pass:** 0
      - **Violated:** 1
      - **Blocking:** 1
      - **Waived:** 0
      - **Not applicable:** 0
      - **Errors:** 0
      - **Advisory-only rules:** 0

      ### Deterministic blockers

      | Rule | Check | Location | Reason |
      | --- | --- | --- | --- |
      | \`security.no-secrets\` | \`regex:AWS_ACCESS_KEY\` | \`src/config.ts:42\` | Found AWS access key in source |

      ### Deterministic warnings

      _None._

      ### Waivers applied

      _None._

      ### Analyzer findings

      _No analyzer checks ran._

      ### Repair

      Re-run after fixes:

      \`\`\`bash
      rulebound check --base main
      \`\`\`

      ---
      _Generated by \`rulebound check --format pr-markdown\`._"
    `)
  })

  it("case 3: non-blocking deterministic warning", () => {
    const report = makeReport({
      status: "PASSED_WITH_WARNINGS",
      summary: { total: 1, violated: 1, blocking: 0 },
      ruleStatuses: [makeRuleStatus({ ruleId: "style.todo-comments", status: "VIOLATED", blocking: false })],
      results: [
        makeResult({
          ruleId: "style.todo-comments",
          checkId: "regex:TODO",
          status: "VIOLATED",
          source: "regex",
          blocking: false,
          confidence: "high",
          reason: "TODO comment without owner",
          evidence: { filePath: "src/utils.ts", line: 10 },
        }),
      ],
    })
    expect(renderPrMarkdown(report, RERUN)).toMatchInlineSnapshot(`
      "## rulebound check — **PASSED_WITH_WARNINGS**

      - **Pass:** 0
      - **Violated:** 1
      - **Blocking:** 0
      - **Waived:** 0
      - **Not applicable:** 0
      - **Errors:** 0
      - **Advisory-only rules:** 0

      ### Deterministic blockers

      _None._

      ### Deterministic warnings

      | Rule | Check | Location | Reason |
      | --- | --- | --- | --- |
      | \`style.todo-comments\` | \`regex:TODO\` | \`src/utils.ts:10\` | TODO comment without owner |

      ### Waivers applied

      _None._

      ### Analyzer findings

      _No analyzer checks ran._

      ### Repair

      Re-run after fixes:

      \`\`\`bash
      rulebound check --base main
      \`\`\`

      ---
      _Generated by \`rulebound check --format pr-markdown\`._"
    `)
  })

  it("case 4: valid waiver downgrades blocker to advisory", () => {
    const waivedResult = makeResult({
      ruleId: "security.no-eval",
      checkId: "regex:eval",
      status: "VIOLATED",
      source: "regex",
      blocking: true,
      reason: "Use of eval()",
      evidence: { filePath: "src/legacy.ts", line: 7 },
      waived: { reason: "Legacy code, tracked in #1234", expires: "2099-01-01" },
    })
    const report = makeReport({
      status: "PASSED_WITH_WARNINGS",
      summary: { total: 1, violated: 1, blocking: 0, waived: 1 },
      ruleStatuses: [makeRuleStatus({ ruleId: "security.no-eval", status: "ADVISORY" })],
      results: [waivedResult],
      waiversApplied: [
        {
          result: waivedResult,
          waiver: makeWaiver({
            rule: "security.no-eval",
            reason: "Legacy code, tracked in #1234",
            owner: "@alice",
            expires: "2099-01-01",
          }),
          expired: false,
        },
      ],
    })
    expect(renderPrMarkdown(report, RERUN)).toMatchInlineSnapshot(`
      "## rulebound check — **PASSED_WITH_WARNINGS**

      - **Pass:** 0
      - **Violated:** 1
      - **Blocking:** 0
      - **Waived:** 1
      - **Not applicable:** 0
      - **Errors:** 0
      - **Advisory-only rules:** 1

      ### Deterministic blockers

      _None._

      ### Deterministic warnings

      _None._

      ### Waivers applied

      | Rule | Path | Owner | Expires | Reason |
      | --- | --- | --- | --- | --- |
      | \`security.no-eval\` | \`src/legacy.ts\` | @alice | 2099-01-01 | Legacy code, tracked in #1234 |

      ### Analyzer findings

      _No analyzer checks ran._

      ### Repair

      Re-run after fixes:

      \`\`\`bash
      rulebound check --base main
      \`\`\`

      ---
      _Generated by \`rulebound check --format pr-markdown\`._"
    `)
  })

  it("case 5: expired waiver re-blocks", () => {
    const expiredResult = makeResult({
      ruleId: "security.no-eval",
      checkId: "regex:eval",
      status: "VIOLATED",
      source: "regex",
      blocking: true,
      reason: "Use of eval()",
      evidence: { filePath: "src/legacy.ts", line: 7 },
    })
    const report = makeReport({
      status: "FAILED",
      summary: { total: 1, violated: 1, blocking: 1 },
      ruleStatuses: [makeRuleStatus({ ruleId: "security.no-eval", status: "VIOLATED" })],
      results: [expiredResult],
      waiversApplied: [
        {
          result: expiredResult,
          waiver: makeWaiver({
            rule: "security.no-eval",
            reason: "Legacy code, tracked in #1234",
            owner: "@alice",
            expires: "2020-01-01",
          }),
          expired: true,
        },
      ],
    })
    expect(renderPrMarkdown(report, RERUN)).toMatchInlineSnapshot(`
      "## rulebound check — **FAILED**

      - **Pass:** 0
      - **Violated:** 1
      - **Blocking:** 1
      - **Waived:** 0
      - **Not applicable:** 0
      - **Errors:** 0
      - **Advisory-only rules:** 0

      ### Deterministic blockers

      | Rule | Check | Location | Reason |
      | --- | --- | --- | --- |
      | \`security.no-eval\` | \`regex:eval\` | \`src/legacy.ts:7\` | Use of eval() |

      ### Deterministic warnings

      _None._

      ### Waivers applied

      | Rule | Path | Owner | Expires | Reason |
      | --- | --- | --- | --- | --- |

      **Expired waivers (re-blocking):**
      - \`security.no-eval\` — expired 2020-01-01 (owner: @alice)

      ### Analyzer findings

      _No analyzer checks ran._

      ### Repair

      Re-run after fixes:

      \`\`\`bash
      rulebound check --base main
      \`\`\`

      ---
      _Generated by \`rulebound check --format pr-markdown\`._"
    `)
  })

  it("case 6: analyzer findings", () => {
    const report = makeReport({
      status: "FAILED",
      summary: { total: 2, violated: 2, blocking: 1 },
      ruleStatuses: [
        makeRuleStatus({ ruleId: "java.pmd", status: "VIOLATED" }),
        makeRuleStatus({ ruleId: "java.checkstyle", status: "VIOLATED", blocking: false }),
      ],
      results: [
        makeResult({
          ruleId: "java.pmd",
          checkId: "analyzer:pmd",
          status: "VIOLATED",
          source: "analyzer",
          confidence: "high",
          blocking: true,
          reason: "PMD: AvoidPrintStackTrace at src/Main.java:12",
          evidence: { filePath: "src/Main.java", line: 12, analyzerReport: "build/pmd.xml" },
        }),
        makeResult({
          ruleId: "java.checkstyle",
          checkId: "analyzer:checkstyle",
          status: "VIOLATED",
          source: "analyzer",
          confidence: "high",
          blocking: false,
          reason: "Checkstyle: LineLength at src/Main.java:50",
          evidence: { filePath: "src/Main.java", line: 50 },
        }),
      ],
    })
    expect(renderPrMarkdown(report, RERUN)).toMatchInlineSnapshot(`
      "## rulebound check — **FAILED**

      - **Pass:** 0
      - **Violated:** 2
      - **Blocking:** 1
      - **Waived:** 0
      - **Not applicable:** 0
      - **Errors:** 0
      - **Advisory-only rules:** 0

      ### Deterministic blockers

      | Rule | Check | Location | Reason |
      | --- | --- | --- | --- |
      | \`java.pmd\` | \`analyzer:pmd\` | \`src/Main.java:12\` | PMD: AvoidPrintStackTrace at src/Main.java:12 |

      ### Deterministic warnings

      | Rule | Check | Location | Reason |
      | --- | --- | --- | --- |
      | \`java.checkstyle\` | \`analyzer:checkstyle\` | \`src/Main.java:50\` | Checkstyle: LineLength at src/Main.java:50 |

      ### Waivers applied

      _None._

      ### Analyzer findings

      - Total: 2
      - Blocking: 1

      ### Repair

      Re-run after fixes:

      \`\`\`bash
      rulebound check --base main
      \`\`\`

      ---
      _Generated by \`rulebound check --format pr-markdown\`._"
    `)
  })

  it("case 7: parse/schema errors", () => {
    const report = makeReport({
      status: "FAILED",
      summary: { total: 0, error: 0 },
      parseErrors: [
        {
          ruleId: "broken.rule",
          errors: ["checks[0].type: unknown check type", "checks[0].path: required"],
        },
        {
          ruleId: "another.rule",
          errors: ["checks must be an array"],
        },
      ],
    })
    expect(renderPrMarkdown(report, RERUN)).toMatchInlineSnapshot(`
      "## rulebound check — **FAILED**

      - **Pass:** 0
      - **Violated:** 0
      - **Blocking:** 0
      - **Waived:** 0
      - **Not applicable:** 0
      - **Errors:** 0
      - **Advisory-only rules:** 0

      ### Rule schema errors

      - \`broken.rule\`
        - checks[0].type: unknown check type
        - checks[0].path: required
      - \`another.rule\`
        - checks must be an array

      ### Deterministic blockers

      _None._

      ### Deterministic warnings

      _None._

      ### Waivers applied

      _None._

      ### Analyzer findings

      _No analyzer checks ran._

      ### Repair

      Re-run after fixes:

      \`\`\`bash
      rulebound check --base main
      \`\`\`

      ---
      _Generated by \`rulebound check --format pr-markdown\`._"
    `)
  })
})

describe("renderPrMarkdown — product boundary language", () => {
  // Guards that the report cannot collapse the deterministic / advisory
  // distinction. These are independent of any single snapshot so a future
  // wording change can update snapshots without silently weakening the
  // contract.
  const report: DeterministicReport = {
    status: "FAILED",
    summary: { total: 3, pass: 0, violated: 3, notApplicable: 0, error: 0, blocking: 1, waived: 1 },
    ruleStatuses: [{ ruleId: "advisory.r", title: "advisory.r", checkCount: 0, status: "ADVISORY", blocking: false }],
    parseErrors: [],
    results: [
      {
        ruleId: "det.blocker",
        checkId: "regex:secret",
        status: "VIOLATED",
        source: "regex",
        deterministic: true,
        confidence: "exact",
        blocking: true,
        reason: "blocker",
      },
      {
        ruleId: "det.warning",
        checkId: "regex:todo",
        status: "VIOLATED",
        source: "regex",
        deterministic: true,
        confidence: "high",
        blocking: false,
        reason: "warning",
      },
      {
        ruleId: "waived.rule",
        checkId: "regex:legacy",
        status: "VIOLATED",
        source: "regex",
        deterministic: true,
        confidence: "exact",
        blocking: true,
        reason: "waived blocker",
        waived: { reason: "tracked", expires: "2099-01-01" },
      },
    ],
    waiversApplied: [
      {
        result: {
          ruleId: "waived.rule",
          checkId: "regex:legacy",
          status: "VIOLATED",
          source: "regex",
          deterministic: true,
          confidence: "exact",
          blocking: true,
          reason: "waived blocker",
        },
        waiver: { rule: "waived.rule", reason: "tracked", owner: "@alice", expires: "2099-01-01" },
        expired: false,
      },
    ],
  }
  const out = renderPrMarkdown(report, "rulebound check")

  it("keeps deterministic blockers, warnings, waivers, analyzer findings, and repair as distinct sections", () => {
    expect(out).toContain("### Deterministic blockers")
    expect(out).toContain("### Deterministic warnings")
    expect(out).toContain("### Waivers applied")
    expect(out).toContain("### Analyzer findings")
    expect(out).toContain("### Repair")
  })

  it("surfaces advisory-only rule count in the summary so they cannot be confused with blockers", () => {
    expect(out).toContain("**Advisory-only rules:** 1")
  })

  it("never lists a waived finding under deterministic blockers", () => {
    const blockersSection = out.split("### Deterministic blockers")[1]?.split("###")[0] ?? ""
    expect(blockersSection).not.toContain("waived.rule")
  })

  it("includes the repair command verbatim under the Repair section", () => {
    expect(out).toMatch(/### Repair[\s\S]+```bash\nrulebound check\n```/)
  })
})
